# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-R6xhctlX4coyyd3CDQBTzzFVs1DxQUc
"""


from fastapi import FastAPI, Form, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

app = FastAPI()

# Serve static files (CSS, JS, etc.)
app.mount("/static", StaticFiles(directory="static"), name="static")

# Set up HTML templates
templates = Jinja2Templates(directory="templates")

# Home page (frontend)
@app.get("/", response_class=HTMLResponse)
def home(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

# Endpoint to receive data from frontend
@app.post("/submit", response_class=HTMLResponse)
def submit_data(request: Request, name: str = Form(...), email: str = Form(...), message: str = Form(...)):
    result = f"Hello {name}! Your message has been received."
    return templates.TemplateResponse("index.html", {"request": request, "result": result})

import os

# Create the static and templates directories if they don't exist
if not os.path.exists("static"):
    os.makedirs("static")

if not os.path.exists("templates"):
    os.makedirs("templates")

print("Directories 'static' and 'templates' created successfully (if they didn't exist).")

