# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1GlfRubhFsh7y-leaZ8FCN60mi2kBOI
"""

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI()

# Allow frontend to access backend (CORS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Change "*" to your frontend URL in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Define what data you expect from frontend
class FrontendData(BaseModel):
    name: str
    email: str
    message: str

# Example POST route to receive data
@app.post("/submit-data")
async def receive_data(data: FrontendData):
    print("Received data:", data.dict())
    # You can process/store data here
    return {"status": "success", "received": data.dict()}

# Example GET route to send data to frontend
@app.get("/get-data")
async def send_data():
    return {"message": "Hello from backend!", "data": [1, 2, 3]}

